### ISSUE TITLE
empty variables and missing assignments in wICA

### ISSUE THREAD

**Issue by ArtuDitu** [lcnhappe/happe#1]
Hey,

great idea to put together these tools and prepare a fully automated pipeline.

I tried to use it and encounter problems from the beginning.

wICA function doesn't return any values
I think the problem is with assignments of variable: IC
it's simply empty. 

the function 'runamica' doesn't calculate OUTEEG.icaact
As far as I know you are missing this in wICA:

OUTEEG.icaact = (OUTEEG.icaweights*OUTEEG.icasphere)*OUTEEG.data(OUTEEG.icachansind,:);
Let me know if im not correct

Did you test your pipeline? 
I'm looking forward to your answer. 

Best,
Artur

**Comment by LaurelJoyGabardDurnam** [comment]
Hi Artur, 
Thanks for your interest in our software! 
We've encountered the error you describe where wICA doesn't return values, and it's actually tied to a memory setting in EEGLAB. In our README, we include a slide on what the EEGLAB memory settings should be set to for HAPPE to run. Have you tried checking your settings? 

We'll also update the code to give an error message when this happens explaining that this situation is most likely due to your memory settings and to check the README for how to adjust those.

Let me know if you continue to get the error after adjusting the memory settings in EEGLAB?

We've tested the pipeline across users on both Macs and PCs over the past year, so we should be able to get to the bottom of this, it's been working for others!

**Comment by ArtuDitu** [comment]
Hey, 

thanks for your answer. 
It was exactly the problem that you described. 
I initially changed the eeglab options but due to  different eeglab versions in the path the problem still occurred. However, now it's solved. 

I have another question concerning second figure generated with your pipeline. Namely, the figure summarizing ICs, wICS and their difference. What are the numbers on the x-axis? 
In your example you have ~65 and  for my dataset (sampling rate 1024 and around 70 minutes of recording) the number was ~3000.

ps. I added sensor layout and loading function for ANT 64 and 128 systems. I can send it to you if you want to include other systems in your script. 

Thanks a lot for fast communication.

**Comment by ArtuDitu** [comment]
I found an answer to the above question in the script. Sorry to bother :)

**Comment by LaurelJoyGabardDurnam** [comment]
Hi again Artur, 
Great! Glad that's sorted. 
And yes, we'd love to add the layout and loading for ANT systems,  if you wouldn't mind sending that along? (laurel.gabarddurnam@gmail.com). Thanks so much!
Cheers,
Laurel
